GET http://localhost:3000/users?order=newest&offset=0&limit=5

###

POST http://localhost:3000/users
Content-Type: application/json

{
 "email": "test-11@test.com",
"firstName": "Adwa",
"lastName": "Kim",
"address": "Seoul, Korea",
"userPreference": {
    "receiveEmail": true
}
}

###
GET http://localhost:3000/users/31194866-d63e-48ad-bd6a-f670dc02f650

###
PATCH http://localhost:3000/users/31194866-d63e-48ad-bd6a-f670dc02f650
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "ssdw",
    "userPreference":{
        "receiveEmail":false
    }
}
###
DELETE http://localhost:3000/users/8c65f9da-62fc-49d0-ae62-f3a183c36a17
